routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', 'HomeController@index')->name('home');
Route::prefix('admin')->middleware('auth')->namespace('Admin')->group(function () {
    Route::resources([
        'categories' => 'CategoryController',
        'products' => 'ProductController'
    ]);
    Route::prefix('orders')->group(function() {
        Route::get('/', 'OrderController@index')->name('orders.index');
        Route::get('{order}/items', 'OrderController@items')->name('order.items');
        
    });
    
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = [
        'name', 'status', 'description', 'image'
    ];

    public function categories()
    {
        return $this->hasMany(Category::class);
    }

    public function childrenCategories()
    {
        return $this->hasMany(Category::class)->with('categories'); // will give you as many levels as it could find
    }

    public function parentCategory()
    {
        return $this->belongsTo(Category::class, 'category_id');
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use App\Http\Controllers\Controller;
use App\Models\Category;
use Illuminate\Support\Facades\Storage;

class CategoryController extends Controller
{
    public function index(Request $request)
    {
        $categories = Category::when($request->has('term'), function ($query) use ($request) {
            return $query->where('name', 'like', '%' . $request->input('term') . '%');
        })->paginate(10);
        return view('admin.categories.list', compact('categories'));
    }

    public function create()
    {
        $parentCategories = Category::whereNull('category_id')->get();
        return view('admin.categories.form', compact('parentCategories'));
    }

    public function store(Request $request)
    {
        $fields = $request->validate([
            'name' => 'required|max:191|unique:categories',
            'status' => 'nullable|boolean',
            'image' => 'nullable|file|image',
        ]);
        $fields['description'] = $request->input('description');
        $fields['status'] = $fields['status'] ?? 0;
        if ($request->hasFile('image')) {
            $fields['image'] = $request->file('image')->store('uploads/categories', 'public');
        }
        $category = new Category($fields);
        $category->parentCategory()->associate($request->input('category_id'));
        $category->save();
        return redirect()->route('categories.index');
    }

    public function edit(Category $category)
    {
        $parentCategories = Category::where('id', '<>', $category->id)->whereNull('category_id')->get();
        return view('admin.categories.form', compact('parentCategories', 'category'));
    }

    public function update(Request $request, Category $category)
    {
        $fields = $request->validate([
            'name' => ['required', 'max:191', Rule::unique('categories')->ignore($category->id)],
            'status' => 'nullable|boolean',
            'image' => 'nullable|file|image',
        ]);
        $fields['description'] = $request->input('description');
        $fields['status'] = $fields['status'] ?? 0;
        if ($request->hasFile('image')) {
            Storage::disk('public')->delete($category->image);
            $fields['image'] = $request->file('image')->store('uploads/categories', 'public');
        }
        $category->fill($fields);
        $category->parentCategory()->associate($request->input('category_id'));
        $category->save();
        return redirect()->route('categories.index');
    }
}

app/Http/Controllers/Api/CategoriesController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\Http\Resources\CategoryResource;
use App\Http\Resources\ProductResource;
use App\Models\Category;
use App\Models\Product;

class CategoriesController extends Controller
{
    public function index()
    {
        // Return all categoties that are not parents
        $category = Category::where('status', 1)->whereNotIn('id', Category::whereNotNull('category_id')->pluck('category_id')->toArray())->get();
        return CategoryResource::collection($category);
    }

    public function relatedProducts($category)
    {
        $products = Product::where('category_id', $category)->where('status', 1)->where('quantity', '>', 0)->get();
        return ProductResource::collection($products);
    }
}

resources/views/admin/categories/form.blade.php
@extends('layouts.dashboard')

@section('content')

<div class="main-card mb-3 card">
    <div class="card-body">
        <h5 class="card-title">Add new Category</h5>
        <form method="POST" action="{{ empty($category) ? route('categories.store') : route('categories.update', $category) }}" enctype="multipart/form-data">
            @csrf
            @isset($category) @method('PUT') @endisset
            <div class="form-group">
                <label>Category name</label>
                <input type="text" class="form-control" name="name" value="{{ old('name', $category->name ?? null) }}">
                @error('name')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
            <div class="form-group">
                <label>Parent category</label>
                <select class="form-control" name="category_id">
                    <option></option>
                    @foreach ($parentCategories as $parentCategory)
                        <option value="{{ $parentCategory->id }}" @isset($category->parentCategory) {{ $parentCategory->id === $category->parentCategory->id ? 'selected' : null }} @endisset>{{ $parentCategory->name }}</option>
                    @endforeach
                </select>
                @error('category_id')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
            <div class="form-group">
                <label>Description</label>
                <textarea class="form-control" name="description">{{ old('description', $category->description ?? null) }}</textarea>
                @error('name')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
            <div class="form-group">
                <label>Image</label>
                <input type="file" name ="image" />
            </div>
            <div class="form-group">
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="checkbox" name="status" value="1" {{ 0 !== old('published', $category->status ?? 0) || !isset($category) ? 'checked' : null }}>
                    <label class="form-check-label">Is published?</label>
                </div>
                @error('published')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
            <button type="submit" class="btn btn-success">Submit</button>
        </form>
    </div>
</div>

@endsection

resources/views/admin/categories/list.blade.php
@extends('layouts.dashboard')

@section('content')

<div class="main-card mb-3 card">
    <div class="card-body">
        <h5 class="card-title">
            Categories List
        </h5>
        <div class="card-body">
            <form>
                <div class="input-group">
                    <input type="text" class="form-control" name="term" value="{{ request('term') }}">
                    <div class="input-group-append">
                        <button class="btn btn-success" type="submit"><i class="fas fa-search"></i></button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="main-card mb-3 card">
    <div class="card-body">
        <table class="mb-0 table table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Active?</th>
                    <th>Parent Category</th>
                    <th>Image</th>
                    <th>Description</th>
                    <th>Created At</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach($categories as $category)
                    <tr id="model-{{ $category->id }}">
                        <td>{{ $category->name }}</td>                        
                        <td><span class="badge badge-{{ $category->status ? 'success' : 'warning' }}">&nbsp;{{ $category->status ? 'Yes' : 'No' }}</span></td>
                        <td>{{ optional($category->parentCategory)->name }}</td>
                        <td><img src="{{ asset($category->image) }}" width="80px" class="img img-responsive"/></td>
                        <td>{{ substr($category->description, 0, 40) }}</td>
                        <td>{{ $category->created_at }}</td>
                        <td>
                            <a href="{{ route('categories.edit', $category) }}" class="font-icon-wrapper font-icon-md">
                                <i class="metismenu-icon pe-7s-pen icon-gradient bg-grow-early"></i>
                            </a>
                            {{-- <a href="javascript:;" class="font-icon-wrapper font-icon-md" onclick="destroy('{{ route('categories.destroy', ['id' => $category->id]) }}')">
                                <i class="metismenu-icon pe-7s-trash icon-gradient bg-strong-bliss"></i>
                            </a> --}}
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
        @isset($categories)
        <div class="col">
            {{ $categories->links() }}
        </div>
        @endisset
    </div>
</div>
@endsection